server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.data.cassandra: ${CASSANDRA_LOG_LEVEL:INFO}

spring:
  application:
    name: ${APPLICATION_NAME:authservice}

  cassandra:
    keyspace-name: ${CASSANDRA_KEYSPACE:scheduler}
    schema-action: ${CASSANDRA_SCHEMA_ACTION:CREATE_IF_NOT_EXISTS}

  data:
    cassandra:
      username: ${CASSANDRA_USERNAME:QnoMwZSZDbBLryRJkOQLQBsF}
      password: ${CASSANDRA_PASSWORD:jpBkCGyEUzSBJF0,U1bmqxwWn+Fb5jqch-4r2l4itPRnkij0jQaLIRnwT-wYHnvWGrK7iU,ZKNcXaow3RyaQkumE01c7hexP1uH1mXTQGTGzjSCpK+U4HHJ8-hxm,YEN}

datastax:
  astra:
    secure-connect-bundle: ${ASTRA_SECURE_CONNECT_BUNDLE:src/main/resources/secure-connect.zip}

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health
#  endpoint:
#    health:
#      show-details: always